[package]
name = "fact_db"
version = "0.4.0"
edition = "2021"

[dependencies]
shared_deps = { path = "../shared_deps" }
bevy = { version = "0.14.2", default-features = false }
serde = { version = "1.0.197", features = ["serde_derive"] }
lazy_static = "1.5.0"
maplit = "1.0.2"
