[package]
name = "fact_db"
version = "0.4.0"
edition = "2021"

[dependencies]
shared_deps = { path = "../shared_deps" }
bevy = { workspace = true }
serde = { workspace = true }
lazy_static = "1.5.0"
maplit = { workspace = true }
