repos:
  - repo: local
    hooks:
      - id: cargo-test
        name: cargo test
        description: Run cargo test
        entry: cargo test --workspace
        language: rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Run the Clippy linter on the package.
        entry: cargo clippy --workspace --all-targets --all-features -- -Dwarnings
        language: rust
        files: \.rs$
        pass_filenames: false
      # - id: cargo-format
      #   name: cargo format
      #   description: Run the cargo format
      #   entry: cargo fmt --all -- --check
      #   language: rust
      #   files: \.rs$
      #   pass_filenames: false
