[workspace]
resolver = "2"
members = [
    "common",
    "minigames/four_in_row",
    "minigames/endless_shooter",
    "minigames/tic_tac_toe",
    "minigames/higher_lower",
    "run",
    "text_keys",
]
default-members = ["run"]
