[workspace]
resolver = "2"
members = [
    "common",
    "minigames/four_in_row",
    "minigames/endless_shooter",
    "minigames/tic_tac_toe",
    "minigames/higher_lower",
    "minigames/rhythm",
    "run",
    "text_keys",
    "fact_db",
    "shared_deps",
]
default-members = ["run"]
