[package]
name = "sardips_higher_lower"
version = "0.4.0"
edition = "2021"

[dependencies]
sardips_core = { path = "../../core" }
shared_deps = { path = "../../shared_deps" }
text_keys = { path = "../../text_keys" }
bevy = { version = "0.14.2", default-features = false }
