[package]
name = "sardips_higher_lower"
version = "0.6.0"
edition = "2021"

[dependencies]
sardips_core = { path = "../../core" }
shared_deps = { path = "../../shared_deps" }
text_keys = { path = "../../text_keys" }
bevy = { workspace = true }
