[package]
name = "sardips_four_in_row"
version = "0.7.0"
edition = "2021"

[dependencies]
sardips_core = { path = "../../core" }
shared_deps = { path = "../../shared_deps" }
lazy_static = { workspace = true }
bevy = { workspace = true }
