[package]
name = "sardips_four_in_row"
version = "0.4.0"
edition = "2021"

[dependencies]
sardips_core = { path = "../../core" }
shared_deps = { path = "../../shared_deps" }
lazy_static = "1.4.0"
bevy = { version = "0.14.2", default-features = false }
