[package]
name = "sardips_endless_shooter"
version = "0.4.0"
edition = "2021"

[dependencies]
shared_deps = { path = "../../shared_deps" }
sardips_core = { path = "../../core" }
text_keys = { path = "../../text_keys" }
bevy = { version = "0.14.2", default-features = false }
maplit = "1.0.2"
