[package]
name = "sardips_endless_shooter"
version = "0.6.0"
edition = "2021"

[dependencies]
shared_deps = { path = "../../shared_deps" }
sardips_core = { path = "../../core" }
text_keys = { path = "../../text_keys" }
bevy = { workspace = true }
maplit = { workspace = true }
